### ISSUE TITLE
Incorrect yaml output for multiline attribution string

### ISSUE THREAD

**Issue by benwiley4000** [licensee/licensee#358]
### Describe the bug

When an attribution string contains multiple lines (an example is the `accepts` module from npm, version 1.3.3), the output doesn't come out as correct yaml. For `accepts`, we get this output:

```yaml
License:        MIT
Matched files:  LICENSE
LICENSE:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>
Copyright (c) 2015 Douglas Christopher Wilson <doug@somethingdoug.com>
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
```

Yaml parsers (such as `js-yaml` from npm) don't know how to parse this and I get this error:

```
(node:18392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 7, column 13:
      Confidence:    100.00%
```

I consulted [this guide](https://yaml-multiline.info/) to handling multiline strings in yaml and I found this is the correct output format:

```yaml
License:        MIT
Matched files:  LICENSE
LICENSE:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>\\nCopyright (c) 2015 Douglas Christopher Wilson <doug@somethingdoug.com>"
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
```

As you can see we surround the multiline string in double quotes, and instead of a literal newline we use `\\n` (regular `\n` is ignored). Also we would clearly need to escape any double quotes that appear in the attribution string, if there were any.

### Steps to reproduce the behavior

1. `licensee detect --remote --no-packages --no-readme jshttp/accepts`
2. You should see the same poorly formed yaml string as I printed above

### Expected behavior

Yaml I can parse appropriately
