### ISSUE TITLE
License `LGPL-3.0-or-later` is not detected

### ISSUE THREAD

**Issue by NatoBoram** [licensee/licensee#631]
### Describe the bug

[`lgpl-3.0.md`](https://www.gnu.org/licenses/lgpl-3.0.md) is not detected as `LGPL-3.0-or-later` despite being an official license file distributed by [gnu.org](https://www.gnu.org/licenses/lgpl-3.0.html).

Additionally, `LGPL-3.0-or-later` from `package.json` is not detected as `LGPL-3.0-or-later` despite being copied from the [SPDX License List](https://spdx.org/licenses/).

### Steps to reproduce the behavior

1. Obtain [`lgpl-3.0.md`](https://www.gnu.org/licenses/lgpl-3.0.md) from [gnu.org/licenses/lgpl-3.0.html](https://www.gnu.org/licenses/lgpl-3.0.html)
2. Put it in a directory as `LICENSE.md`
3. Run `licensee`
4. See `License:       NOASSERTION`

­

1. Put `LGPL-3.0-or-later` in `package.json`
2. Run `licensee`
3. See `License:     NOASSERTION`

### Expected behavior

See `License:        LGPL-3.0-or-later`.

### Screenshots

![licensee](https://user-images.githubusercontent.com/10495562/211236403-23cf3de0-d739-4f33-a246-0a4a51a1be1d.png)

![LICENSE.md](https://user-images.githubusercontent.com/10495562/211237051-b0a2968a-71ef-40f9-93c8-caa7c0f26f36.png)

### Additional context

I raised a [ticket](https://support.github.com/ticket/personal/0/1957034) with GitHub support since it affects the GitHub website, but from the output of `licensee`, I'm not sure if it's just GitHub.

---

**Edit:** I was using `v9.14.1`. `v9.16.0` has a slightly different output.

```yaml
License:        NOASSERTION
Matched files:  LICENSE.md, package.json
LICENSE.md:
  Content hash:  bf02267acafaf5f27f9e377e2770f7adfcfaa94f
  Confidence:    98.50%
  Matcher:       Licensee::Matchers::Dice
  License:       LGPL-3.0
  Closest non-matching licenses:
    LGPL-3.0 similarity:        98.50%
    CERN-OHL-P-2.0 similarity:  28.73%
    Artistic-2.0 similarity:    24.21%
package.json:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::NpmBower
  License:     NOASSERTION
```

It seems like the license file is now detected, but the `package.json` still isn't and the whole project isn't detected as `LGPL-3.0-or-later`.
